packages:
  - mc
  - git
  - gitflow

git:
   userName: 'Ivan I. Atanasov'
   userEmail: 'i.atanasov77@gmail.com'
     
services:
  gitlab: "False"
  jenkins: "True"

phpModules:
  - intl
