packages:
  - mc
  - git
  - gitflow

git:
   userName: 'Ivan I. Atanasov'
   userEmail: 'i.atanasov77@gmail.com'
     
services:
  gitlab: "False"
  maven: "False"
  jenkins: "True"
  jenkinsPort: "8080"
  jenkinsPlugins:
    - jobConfigHistory
    - git
    #- ftppublisher
    - publish-over
    - publish-over-ftp
    - phing

phpModules:
  - intl
