---
- name: Install python-docker on CentOS 7
  yum:
    name=python-docker
    state=present
    
- name: Get infos on network
  docker_network_info:
    name: dob-network
  register: result
  
- name: Add dob-network to docker host ...
  command: docker network create --driver bridge dob-network
  when: not result.exists
