---
- fail: msg=" jenkins-swarm | Missing parameters!"
  when: jenkins_remote_username == '' or jenkins_remote_password == ''

- name: jenkins-swarm | Create jenkins user
  user: name={{ jenkins_user }} password={{ jenkins_password }} update_password=always comment="Jenkins user" home={{ jenkins_home }} shell={{ jenkins_shell }}
  ignore_errors: true
  become: true

- name: jenkins-swarm | Create base directory
  file:
    dest="{{ jenkins_slave_home }}"
    state=directory
    owner="{{ jenkins_user }}"
    group="{{ jenkins_group }}"
  tags: jenkins_swarm_setup
  become: true
  
- name: jenkins-swarm | Download Jenkins Swarm Client
  get_url: dest={{ jenkins_slave_home }}/swarm-client-{{ jenkins_swarm_client_version }}-jar-with-dependencies.jar url={{ jenkins_swarm_client_url }}/{{ jenkins_swarm_client_version }}/swarm-client-{{ jenkins_swarm_client_version }}.jar owner={{ jenkins_user }} group={{ jenkins_group }}
  tags: jenkins_swarm_setup
  become: true
  
- set_fact: mydate="#{{lookup('pipe', 'date \"+%Y%m%d\"')}}"
- debug: var=ansible_date_time
- debug: msg="The current date is {{ ansible_date_time.date }} and {{ mydate }}"

- name: Set slave name with date
  set_fact: jenkins_slave_name={{ jenkins_slave_name }}-{{ ansible_date_time.date }}

- debug: msg="The slave name is {{ jenkins_slave_name }}"
  
- name: jenkins-swarm | Install swarm client script
  template: src=jenkins-swarm-client.sh.j2 dest=/etc/init.d/jenkins-swarm-client mode=0755
  tags: jenkins_swarm_setup
  become: true

- name: jenkins-swarm | Register machine to jenkins master
  systemd:
    name: jenkins-swarm-client
    state: started
    enabled: yes
  tags: jenkins_swarm_setup
  become: true

- debug: msg=" jenkins-swarm | Register machine to jenkins master /etc/init.d/jenkins-swarm-client"
- debug: msg=" jenkins-swarm | Log available at {{ jenkins_slave_home }}/swarm-client.log"
