---
- name: Deal with the public key
  hosts: jhost.dob.exam
  tasks:
    - name: Create SSH public key
      openssh_keypair:
        path: /tmp/jenkins_key
    - name: Slurp the public key
      slurp:
        src: /tmp/jenkins_key.pub
      register: jenkins_key_pub

    - name: Save the public key
      set_fact:
        jenkins_slave_key: >-
          {{ jenkins_key_pub['content'] | b64decode }}