
variable "ubuntu_version" {
  type    = string
  default = "23.04"
}

variable "version" {
  type    = string
  default = "3"
}

source "vagrant" "autogenerated_1" {
  add_force    = true
  communicator = "ssh"
  provider     = "virtualbox"
  source_path  = "bento/ubuntu-23.04"
}

build {
  sources = ["source.vagrant.autogenerated_1"]

  provisioner "shell" {
    execute_command = "echo 'vagrant' | {{ .Vars }} sudo -S -E bash '{{ .Path }}'"
    script          = "scripts/ubuntu-kde-provision.sh"
  }

  provisioner "shell" {
    execute_command = "echo 'vagrant' | {{ .Vars }} sudo -S -E bash '{{ .Path }}'"
    script          = "scripts/ubuntu-kde-cleanup.sh"
  }

  post-processor "vagrant" {
    output = "builds/ubuntu-${var.ubuntu_version}-kde-2023.02.06-${var.version}.box"
  }
}
